// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearHistory() {
  return window['go']['main']['App']['ClearHistory']();
}

export function CopyToClipboard(arg1) {
  return window['go']['main']['App']['CopyToClipboard'](arg1);
}

export function DeleteItem(arg1) {
  return window['go']['main']['App']['DeleteItem'](arg1);
}

export function GetItems(arg1, arg2) {
  return window['go']['main']['App']['GetItems'](arg1, arg2);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function PinItem(arg1, arg2) {
  return window['go']['main']['App']['PinItem'](arg1, arg2);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SearchItems(arg1) {
  return window['go']['main']['App']['SearchItems'](arg1);
}
