// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {store} from '../models';

export function ClearHistory():Promise<void>;

export function CopyToClipboard(arg1:string):Promise<void>;

export function DeleteItem(arg1:string):Promise<void>;

export function GetImageBase64(arg1:string):Promise<string>;

export function GetItems(arg1:number,arg2:number):Promise<Array<store.Item>>;

export function GetSettings():Promise<store.Settings>;

export function PinItem(arg1:string,arg2:boolean):Promise<void>;

export function SaveSettings(arg1:store.Settings):Promise<void>;

export function SearchItems(arg1:string):Promise<Array<store.Item>>;
